// =========================================================
// SELEÇÃO DO POVO — Base de dados
// Posições normalizadas: GOL, LD, ZAG, LE, VOL, MEI, PD, PE, ATA
// =========================================================

const PLAYERS = [
  // ---------------- GOLEIROS (GOL) ----------------
  { name: "Alisson", pos: "GOL", club: "Liverpool (ING)" },
  { name: "Ederson", pos: "GOL", club: "Fenerbahçe (TUR)" },
  { name: "Weverton", pos: "GOL", club: "Grêmio (BRA)" },
  { name: "Bento", pos: "GOL", club: "Al-Nassr (ARA)" },
  { name: "Lucas Perri", pos: "GOL", club: "Lyon (FRA)" },
  { name: "Léo Jardim", pos: "GOL", club: "Vasco (BRA)" },
  { name: "Rafael", pos: "GOL", club: "São Paulo (BRA)" },
  { name: "Everson", pos: "GOL", club: "Atlético-MG (BRA)" },
  { name: "João Paulo", pos: "GOL", club: "Santos (BRA)" },
  { name: "Marcos Felipe", pos: "GOL", club: "Bahia (BRA)" },
  { name: "Matheus Cunha", pos: "GOL", club: "Flamengo (BRA)" },
  { name: "John", pos: "GOL", club: "Botafogo (BRA)" },
  { name: "Fábio", pos: "GOL", club: "Fluminense (BRA)" },
  { name: "Walter", pos: "GOL", club: "Cuiabá (BRA)" },
  { name: "Gabriel Vasconcelos", pos: "GOL", club: "América-MG (BRA)" },
  { name: "Neto", pos: "GOL", club: "Bournemouth (ING)" },
  { name: "Matheus", pos: "GOL", club: "Braga (POR)" },
  { name: "Ivan", pos: "GOL", club: "Zenit (RUS)" },
  { name: "Kauã Santos", pos: "GOL", club: "Eintracht Frankfurt (ALE)" },
  { name: "Mycael", pos: "GOL", club: "Athletico-PR (BRA)" },
  { name: "Andrew", pos: "GOL", club: "Gil Vicente (POR)" },
  { name: "Matheus Donelli", pos: "GOL", club: "Corinthians (BRA)" },
  { name: "Hugo Souza", pos: "GOL", club: "Corinthians (BRA)" },
  { name: "Léo Linck", pos: "GOL", club: "Athletico-PR (BRA)" },
  { name: "Santos", pos: "GOL", club: "Fortaleza (BRA)" },
  { name: "Marcelo Grohe", pos: "GOL", club: "Al-Kholood (ARA)" },
  { name: "Cleiton", pos: "GOL", club: "Bragantino (BRA)" },
  { name: "Tadeu", pos: "GOL", club: "Goiás (BRA)" },
  { name: "Mailson", pos: "GOL", club: "Al-Taawoun (ARA)" },
  { name: "Ronaldo", pos: "GOL", club: "Atlético-GO (BRA)" },
  { name: "Gabriel Grando", pos: "GOL", club: "Cruzeiro (BRA)" },
  { name: "Keiller", pos: "GOL", club: "Vasco (BRA)" },
  { name: "Caíque", pos: "GOL", club: "Grêmio (BRA)" },
  { name: "Jordi", pos: "GOL", club: "Novorizontino (BRA)" },
  { name: "Gabriel Bubniack", pos: "GOL", club: "Coritiba (BRA)" },

  // ---------------- LATERAIS-DIREITOS (LD) ----------------
  { name: "Wesley", pos: "LD", club: "Roma (ITA)" },
  { name: "Danilo", pos: "LD", club: "Flamengo (BRA)" },
  { name: "Yan Couto", pos: "LD", club: "Borussia Dortmund (ALE)" },
  { name: "Vanderson", pos: "LD", club: "Monaco (FRA)" },
  { name: "Emerson Royal", pos: "LD", club: "Milan (ITA)" },
  { name: "Dodô", pos: "LD", club: "Fiorentina (ITA)" },
  { name: "Arthur", pos: "LD", club: "Bayer Leverkusen (ALE)" },
  { name: "Vinícius Tobias", pos: "LD", club: "Shakhtar Donetsk (UCR)" },
  { name: "William", pos: "LD", club: "Cruzeiro (BRA)" },
  { name: "Mayke", pos: "LD", club: "Palmeiras (BRA)" },
  { name: "Matheuzinho", pos: "LD", club: "Corinthians (BRA)" },
  { name: "Guga", pos: "LD", club: "Fluminense (BRA)" },
  { name: "Tinga", pos: "LD", club: "Fortaleza (BRA)" },
  { name: "Vitinho", pos: "LD", club: "Botafogo (BRA)" },
  { name: "Samuel Xavier", pos: "LD", club: "Fluminense (BRA)" },
  { name: "Natanael", pos: "LD", club: "Coritiba (BRA)" },
  { name: "João Pedro", pos: "LD", club: "Grêmio (BRA)" },
  { name: "Fagner", pos: "LD", club: "Corinthians (BRA)" },
  { name: "Marcos Rocha", pos: "LD", club: "Palmeiras (BRA)" },
  { name: "Mariano", pos: "LD", club: "Atlético-MG (BRA)" },
  { name: "Gilberto", pos: "LD", club: "Bahia (BRA)" },
  { name: "Calegari", pos: "LD", club: "Famalicão (POR)" },
  { name: "Madson", pos: "LD", club: "Athletico-PR (BRA)" },
  { name: "Hayner", pos: "LD", club: "Santos (BRA)" },
  { name: "Rafael Ramos", pos: "LD", club: "Ceará (BRA)" },
  { name: "Pedro Lima", pos: "LD", club: "Wolverhampton (ING)" },
  { name: "JP Chermont", pos: "LD", club: "Santos (BRA)" },
  { name: "Khellven", pos: "LD", club: "CSKA Moscou (RUS)" },
  { name: "Agustín Giay", pos: "LD", club: "Palmeiras (BRA)" },
  { name: "Igor Formiga", pos: "LD", club: "Novorizontino (BRA)" },
  { name: "Costaer", pos: "LD", club: "Inter de Limeira (BRA)" },
  { name: "Gustavo Garcia", pos: "LD", club: "Nacional (POR)" },
  { name: "Lucas Kawan", pos: "LD", club: "Santa Clara (POR)" },
  { name: "Dudu", pos: "LD", club: "Criciúma (BRA)" },
  { name: "Michel", pos: "LD", club: "Palmeiras (BRA)" },

  // ---------------- LATERAIS-ESQUERDOS (LE) ----------------
  { name: "Alex Sandro", pos: "LE", club: "Flamengo (BRA)" },
  { name: "Douglas Santos", pos: "LE", club: "Zenit (RUS)" },
  { name: "Carlos Augusto", pos: "LE", club: "Inter de Milão (ITA)" },
  { name: "Caio Henrique", pos: "LE", club: "Monaco (FRA)" },
  { name: "Ayrton Lucas", pos: "LE", club: "Flamengo (BRA)" },
  { name: "Renan Lodi", pos: "LE", club: "Al-Hilal (ARA)" },
  { name: "Abner", pos: "LE", club: "Lyon (FRA)" },
  { name: "Wendell", pos: "LE", club: "Porto (POR)" },
  { name: "Guilherme Arana", pos: "LE", club: "Atlético-MG (BRA)" },
  { name: "Cuiabano", pos: "LE", club: "Botafogo (BRA)" },
  { name: "Vanderlan", pos: "LE", club: "Palmeiras (BRA)" },
  { name: "Juninho Capixaba", pos: "LE", club: "Bragantino (BRA)" },
  { name: "Lucas Piton", pos: "LE", club: "Vasco (BRA)" },
  { name: "Marlon", pos: "LE", club: "Cruzeiro (BRA)" },
  { name: "Reinaldo", pos: "LE", club: "Grêmio (BRA)" },
  { name: "Hugo", pos: "LE", club: "Botafogo (BRA)" },
  { name: "Alex Telles", pos: "LE", club: "Botafogo (BRA)" },
  { name: "Iago", pos: "LE", club: "Bahia (BRA)" },
  { name: "Gabriel Silva", pos: "LE", club: "Santa Clara (POR)" },
  { name: "Felipe Jonatan", pos: "LE", club: "Fortaleza (BRA)" },
  { name: "Rikelme", pos: "LE", club: "Shabab Al-Ahli (EAU)" },
  { name: "Pedrinho", pos: "LE", club: "Shakhtar Donetsk (UCR)" },
  { name: "Matheus Bidu", pos: "LE", club: "Corinthians (BRA)" },
  { name: "Kaiki Bruno", pos: "LE", club: "Cruzeiro (BRA)" },
  { name: "Victor Luis", pos: "LE", club: "Vasco (BRA)" },
  { name: "Danilo Avelar", pos: "LE", club: "Sem Clube" },
  { name: "Patryck Lanza", pos: "LE", club: "São Paulo (BRA)" },
  { name: "Esquerdinha", pos: "LE", club: "Fluminense (BRA)" },
  { name: "João Henrique", pos: "LE", club: "Criciúma (BRA)" },
  { name: "Luan Cândido", pos: "LE", club: "Bragantino (BRA)" },
  { name: "Kevyson", pos: "LE", club: "Santos (BRA)" },
  { name: "Piquerez", pos: "LE", club: "Palmeiras (BRA)" },
  { name: "Matheus Bahia", pos: "LE", club: "Ceará (BRA)" },
  { name: "Jefferson", pos: "LE", club: "Juventude (BRA)" },
  { name: "Marçal", pos: "LE", club: "Botafogo (BRA)" },
  { name: "Ramon", pos: "LE", club: "Cuiabá (BRA)" },
  { name: "Egídio", pos: "LE", club: "Sem Clube" },
  { name: "Carlinhos", pos: "LE", club: "Portimonense (POR)" },
  { name: "Dalbert", pos: "LE", club: "Sport (BRA)" },
  { name: "Natanael", pos: "LE", club: "Avaí (BRA)" },

  // ---------------- ZAGUEIROS (ZAG) ----------------
  { name: "Marquinhos", pos: "ZAG", club: "PSG (FRA)" },
  { name: "Gabriel Magalhães", pos: "ZAG", club: "Arsenal (ING)" },
  { name: "Bremer", pos: "ZAG", club: "Juventus (ITA)" },
  { name: "Ibañez", pos: "ZAG", club: "Al-Ahli (ARA)" },
  { name: "Léo Pereira", pos: "ZAG", club: "Flamengo (BRA)" },
  { name: "Éder Militão", pos: "ZAG", club: "Real Madrid (ESP)" },
  { name: "Murillo", pos: "ZAG", club: "Nottingham Forest (ING)" },
  { name: "Beraldo", pos: "ZAG", club: "PSG (FRA)" },
  { name: "Robert Renan", pos: "ZAG", club: "Al-Shabab (ARA)" },
  { name: "Natan", pos: "ZAG", club: "Real Betis (ESP)" },
  { name: "Marlon", pos: "ZAG", club: "Los Angeles FC (EUA)" },
  { name: "Diego Carlos", pos: "ZAG", club: "Aston Villa (ING)" },
  { name: "Thiago Silva", pos: "ZAG", club: "Fluminense (BRA)" },
  { name: "Fabrício Bruno", pos: "ZAG", club: "Flamengo (BRA)" },
  { name: "Murilo", pos: "ZAG", club: "Palmeiras (BRA)" },
  { name: "Vitão", pos: "ZAG", club: "Internacional (BRA)" },
  { name: "Junior Alonso", pos: "ZAG", club: "Atlético-MG (BRA)" },
  { name: "João Victor", pos: "ZAG", club: "Vasco (BRA)" },
  { name: "Maicon", pos: "ZAG", club: "Vasco (BRA)" },
  { name: "Wagner Leonardo", pos: "ZAG", club: "Vitória (BRA)" },
  { name: "Cacá", pos: "ZAG", club: "Corinthians (BRA)" },
  { name: "Gustavo Martins", pos: "ZAG", club: "Grêmio (BRA)" },
  { name: "Rodrigo Caio", pos: "ZAG", club: "Grêmio (BRA)" },
  { name: "Gil", pos: "ZAG", club: "Santos (BRA)" },
  { name: "David Luiz", pos: "ZAG", club: "Flamengo (BRA)" },
  { name: "Victor Cuesta", pos: "ZAG", club: "Bahia (BRA)" },
  { name: "Gabriel Paulista", pos: "ZAG", club: "Besiktas (TUR)" },
  { name: "Juan Jesus", pos: "ZAG", club: "Napoli (ITA)" },
  { name: "Titi", pos: "ZAG", club: "Fortaleza (BRA)" },
  { name: "Kanu", pos: "ZAG", club: "Bahia (BRA)" },
  { name: "Joaquim", pos: "ZAG", club: "Tigres (MEX)" },
  { name: "Luan", pos: "ZAG", club: "Toluca (MEX)" },
  { name: "Vitor Reis", pos: "ZAG", club: "Palmeiras (BRA)" },
  { name: "Da Mata", pos: "ZAG", club: "Flamengo (BRA)" },
  { name: "João Marcelo", pos: "ZAG", club: "Cruzeiro (BRA)" },
  { name: "Kaiky", pos: "ZAG", club: "Almería (ESP)" },
  { name: "Gabriel Mercado", pos: "ZAG", club: "Internacional (BRA)" },
  { name: "Chiquinho", pos: "ZAG", club: "Santa Clara (POR)" },
  { name: "Bernardo", pos: "ZAG", club: "Red Bull Salzburg (AUT)" },
  { name: "Lucas Belezi", pos: "ZAG", club: "Athletico-PR (BRA)" },
  { name: "Ruan Tressoldi", pos: "ZAG", club: "São Paulo (BRA)" },
  { name: "Léo Ortiz", pos: "ZAG", club: "Flamengo (BRA)" },
  { name: "Alan Franco", pos: "ZAG", club: "São Paulo (BRA)" },
  { name: "Bruno Méndez", pos: "ZAG", club: "Granada (ESP)" },
  { name: "Igor Rabello", pos: "ZAG", club: "Atlético-MG (BRA)" },
  { name: "Bruno Fuchs", pos: "ZAG", club: "Atlético-MG (BRA)" },
  { name: "Messias", pos: "ZAG", club: "Goiás (BRA)" },
  { name: "Robson Bambu", pos: "ZAG", club: "Braga (POR)" },
  { name: "Eduardo Bauermann", pos: "ZAG", club: "Al-Wehda (ARA)" },
  { name: "Pedro Henrique", pos: "ZAG", club: "Bragantino (BRA)" },
  { name: "Lucas Halter", pos: "ZAG", club: "Botafogo (BRA)" },
  { name: "Adryelson", pos: "ZAG", club: "Botafogo (BRA)" },
  { name: "Naves", pos: "ZAG", club: "Palmeiras (BRA)" },
  { name: "Sabino", pos: "ZAG", club: "São Paulo (BRA)" },
  { name: "Kaique Rocha", pos: "ZAG", club: "Athletico-PR (BRA)" },
  { name: "Gustavo Gómez", pos: "ZAG", club: "Palmeiras (BRA)" },
  { name: "Emanuel Brítez", pos: "ZAG", club: "Fortaleza (BRA)" },
  { name: "Rodrigo Ely", pos: "ZAG", club: "Grêmio (BRA)" },
  { name: "Jemerson", pos: "ZAG", club: "Grêmio (BRA)" },
  { name: "PH", pos: "ZAG", club: "Criciúma (BRA)" },
  { name: "Tobias Figueiredo", pos: "ZAG", club: "Fortaleza (BRA)" },
  { name: "Neris", pos: "ZAG", club: "Vitória (BRA)" },
  { name: "Zé Marcos", pos: "ZAG", club: "Juventude (BRA)" },
  { name: "Lucas Ribeiro", pos: "ZAG", club: "Ceará (BRA)" },
  { name: "Felipe", pos: "ZAG", club: "Sem Clube" },

  // ---------------- VOLANTES (VOL) ----------------
  { name: "Casemiro", pos: "VOL", club: "Manchester United (ING)" },
  { name: "Bruno Guimarães", pos: "VOL", club: "Newcastle (ING)" },
  { name: "Fabinho", pos: "VOL", club: "Al-Ittihad (ARA)" },
  { name: "Éderson", pos: "VOL", club: "Atalanta (ITA)" },
  { name: "Danilo Santos", pos: "VOL", club: "Botafogo (BRA)" },
  { name: "João Gomes", pos: "VOL", club: "Wolverhampton (ING)" },
  { name: "Douglas Luiz", pos: "VOL", club: "Juventus (ITA)" },
  { name: "André", pos: "VOL", club: "Wolverhampton (ING)" },
  { name: "Gabriel Moscardo", pos: "VOL", club: "Reims (FRA)" },
  { name: "Danilo", pos: "VOL", club: "Nottingham Forest (ING)" },
  { name: "Arthur Melo", pos: "VOL", club: "Fiorentina (ITA)" },
  { name: "Vinicius Souza", pos: "VOL", club: "Sheffield United (ING)" },
  { name: "Gerson", pos: "VOL", club: "Flamengo (BRA)" },
  { name: "Zé Rafael", pos: "VOL", club: "Palmeiras (BRA)" },
  { name: "Aníbal Moreno", pos: "VOL", club: "Palmeiras (BRA)" },
  { name: "Villasanti", pos: "VOL", club: "Grêmio (BRA)" },
  { name: "Alisson", pos: "VOL", club: "São Paulo (BRA)" },
  { name: "Pablo Maia", pos: "VOL", club: "São Paulo (BRA)" },
  { name: "Marlon Freitas", pos: "VOL", club: "Botafogo (BRA)" },
  { name: "Gregore", pos: "VOL", club: "Botafogo (BRA)" },
  { name: "Erick", pos: "VOL", club: "Athletico-PR (BRA)" },
  { name: "Fernandinho", pos: "VOL", club: "Athletico-PR (BRA)" },
  { name: "Jean Lucas", pos: "VOL", club: "Bahia (BRA)" },
  { name: "Caio Alexandre", pos: "VOL", club: "Bahia (BRA)" },
  { name: "Allan", pos: "VOL", club: "Botafogo (BRA)" },
  { name: "Jair", pos: "VOL", club: "Vasco (BRA)" },
  { name: "Edenilson", pos: "VOL", club: "Grêmio (BRA)" },
  { name: "Patrick", pos: "VOL", club: "Santos (BRA)" },
  { name: "Rezende", pos: "VOL", club: "Bahia (BRA)" },
  { name: "Lucas Silva", pos: "VOL", club: "Cruzeiro (BRA)" },
  { name: "Thiago Maia", pos: "VOL", club: "Internacional (BRA)" },
  { name: "Matheus Henrique", pos: "VOL", club: "Cruzeiro (BRA)" },
  { name: "Walace", pos: "VOL", club: "Cruzeiro (BRA)" },
  { name: "Nonato", pos: "VOL", club: "Fluminense (BRA)" },
  { name: "Richard Ríos", pos: "VOL", club: "Palmeiras (BRA)" },
  { name: "João Schmidt", pos: "VOL", club: "Santos (BRA)" },
  { name: "Du Queiroz", pos: "VOL", club: "Grêmio (BRA)" },
  { name: "Andrey Santos", pos: "VOL", club: "Strasbourg (FRA)" },
  { name: "Alexsander", pos: "VOL", club: "Al-Ahli (ARA)" },
  { name: "Ronald", pos: "VOL", club: "Swansea City (GUA)" },
  { name: "Matheus França", pos: "VOL", club: "Crystal Palace (ING)" },
  { name: "Dudu", pos: "VOL", club: "Palmeiras (BRA)" },
  { name: "Paulinho", pos: "VOL", club: "Sem Clube" },
  { name: "Ramires", pos: "VOL", club: "Sem Clube" },
  { name: "Rômulo", pos: "VOL", club: "Palmeiras (BRA)" },
  { name: "Petros", pos: "VOL", club: "Sem Clube" },
  { name: "Souza", pos: "VOL", club: "Vasco (BRA)" },
  { name: "Fred", pos: "VOL", club: "Fenerbahçe (TUR)" },
  { name: "Joelinton", pos: "VOL", club: "Newcastle (ING)" },
  { name: "Otávio", pos: "VOL", club: "Atlético-MG (BRA)" },
  { name: "Fausto Vera", pos: "VOL", club: "Atlético-MG (BRA)" },
  { name: "Lucas Evangelista", pos: "VOL", club: "Bragantino (BRA)" },
  { name: "Jady", pos: "VOL", club: "Juventude (BRA)" },
  { name: "Matheus Jussa", pos: "VOL", club: "Cruzeiro (BRA)" },
  { name: "Hércules", pos: "VOL", club: "Fortaleza (BRA)" },
  { name: "Willian Farias", pos: "VOL", club: "Novorizontino (BRA)" },
  { name: "Luan", pos: "VOL", club: "Vitória (BRA)" },
  { name: "Bobsin", pos: "VOL", club: "Santa Clara (POR)" },
  { name: "Gabriel", pos: "VOL", club: "Internacional (BRA)" },
  { name: "Matheus Fernandes", pos: "VOL", club: "Bragantino (BRA)" },

  // ---------------- MEIAS (MEI) ----------------
  { name: "Lucas Paquetá", pos: "MEI", club: "Flamengo (BRA)" },
  { name: "Rodrygo", pos: "MEI", club: "Real Madrid (ESP)" },
  { name: "Andreas Pereira", pos: "MEI", club: "Fulham (ING)" },
  { name: "Claudinho", pos: "MEI", club: "Zenit (RUS)" },
  { name: "Malcom", pos: "MEI", club: "Al-Hilal (ARA)" },
  { name: "Gustavo Scarpa", pos: "MEI", club: "Atlético-MG (BRA)" },
  { name: "Philippe Coutinho", pos: "MEI", club: "Vasco (BRA)" },
  { name: "Oscar", pos: "MEI", club: "Shanghai Port (CHI)" },
  { name: "Raphael Veiga", pos: "MEI", club: "Palmeiras (BRA)" },
  { name: "Matheus Pereira", pos: "MEI", club: "Cruzeiro (BRA)" },
  { name: "Ganso", pos: "MEI", club: "Fluminense (BRA)" },
  { name: "Alan Patrick", pos: "MEI", club: "Internacional (BRA)" },
  { name: "Éverton Ribeiro", pos: "MEI", club: "Bahia (BRA)" },
  { name: "Igor Gomes", pos: "MEI", club: "Atlético-MG (BRA)" },
  { name: "Lucas Moura", pos: "MEI", club: "São Paulo (BRA)" },
  { name: "Estêvão", pos: "MEI", club: "Palmeiras (BRA)" },
  { name: "Lorran", pos: "MEI", club: "Flamengo (BRA)" },
  { name: "Luis Guilherme", pos: "MEI", club: "West Ham (ING)" },
  { name: "Rodrigo Nestor", pos: "MEI", club: "São Paulo (BRA)" },
  { name: "Gabriel Carvalho", pos: "MEI", club: "Internacional (BRA)" },
  { name: "Thalys", pos: "MEI", club: "Palmeiras (BRA)" },
  { name: "Hyoran", pos: "MEI", club: "Internacional (BRA)" },
  { name: "Giuliano", pos: "MEI", club: "Santos (BRA)" },
  { name: "Vina", pos: "MEI", club: "Al-Hazem (ARA)" },
  { name: "Jean Pyerre", pos: "MEI", club: "Sem Clube" },
  { name: "Nikão", pos: "MEI", club: "Athletico-PR (BRA)" },
  { name: "Shaylon", pos: "MEI", club: "Atlético-GO (BRA)" },
  { name: "Luciano", pos: "MEI", club: "São Paulo (BRA)" },
  { name: "Maurício", pos: "MEI", club: "Palmeiras (BRA)" },
  { name: "Bruninho", pos: "MEI", club: "Bragantino (BRA)" },
  { name: "Danielzinho", pos: "MEI", club: "Mirassol (BRA)" },
  { name: "Luan", pos: "MEI", club: "Red Bull Bragantino (BRA)" },
  { name: "Jean Carlos", pos: "MEI", club: "Juventude (BRA)" },
  { name: "Matheusinho", pos: "MEI", club: "Vitória (BRA)" },
  { name: "Lincoln", pos: "MEI", club: "Red Bull Bragantino (BRA)" },

  // ---------------- PONTAS-ESQUERDA (PE) ----------------
  { name: "Vinicius Jr.", pos: "PE", club: "Real Madrid (ESP)" },
  { name: "Gabriel Martinelli", pos: "PE", club: "Arsenal (ING)" },
  { name: "Galeno", pos: "PE", club: "Porto (POR)" },
  { name: "Neymar Jr.", pos: "PE", club: "Santos (BRA)" },
  { name: "Pedro Rocha", pos: "PE", club: "Criciúma (BRA)" },
  { name: "Ferreira", pos: "PE", club: "São Paulo (BRA)" },
  { name: "Everton Cebolinha", pos: "PE", club: "Flamengo (BRA)" },
  { name: "Bruno Henrique", pos: "PE", club: "Flamengo (BRA)" },
  { name: "Wesley", pos: "PE", club: "Al-Nassr (ARA)" },
  { name: "Biel", pos: "PE", club: "Bahia (BRA)" },
  { name: "Pedrinho", pos: "PE", club: "Santos (BRA)" },
  { name: "Jeffinho", pos: "PE", club: "Botafogo (BRA)" },
  { name: "Erick Pulga", pos: "PE", club: "Ceará (BRA)" },
  { name: "Arthur Gomes", pos: "PE", club: "Cruzeiro (BRA)" },
  { name: "Keno", pos: "PE", club: "Fluminense (BRA)" },
  { name: "Clayson", pos: "PE", club: "Cuiabá (BRA)" },

  // ---------------- PONTAS-DIREITA (PD) ----------------
  { name: "Raphinha", pos: "PD", club: "Barcelona (ESP)" },
  { name: "Luiz Henrique", pos: "PD", club: "Zenit (RUS)" },
  { name: "Rayan", pos: "PD", club: "Bournemouth (ING)" },
  { name: "Savinho", pos: "PD", club: "Manchester City (ING)" },
  { name: "Antony", pos: "PD", club: "Manchester United (ING)" },
  { name: "David Neres", pos: "PD", club: "Benfica (POR)" },
  { name: "João Pedro", pos: "PD", club: "Brighton (ING)" },
  { name: "Pepê", pos: "PD", club: "Porto (POR)" },
  { name: "Samuel Lino", pos: "PD", club: "Atlético de Madrid (ESP)" },
  { name: "Tetê", pos: "PD", club: "Panathinaikos (GRE)" },
  { name: "Igor Coronado", pos: "PD", club: "Corinthians (BRA)" },
  { name: "Paulinho", pos: "PD", club: "Atlético-MG (BRA)" },
  { name: "Yuri Alberto", pos: "PD", club: "Corinthians (BRA)" },
  { name: "Gabriel Veron", pos: "PD", club: "Cruzeiro (BRA)" },
  { name: "Vitinho", pos: "PD", club: "Red Bull Bragantino (BRA)" },
  { name: "Ademir", pos: "PD", club: "Bahia (BRA)" },
  { name: "Wesley", pos: "PD", club: "Internacional (BRA)" },
  { name: "Rossi", pos: "PD", club: "Vasco (BRA)" },
  { name: "Marquinhos", pos: "PD", club: "Fluminense (BRA)" },

  // ---------------- CENTROAVANTES (ATA) ----------------
  { name: "Endrick", pos: "ATA", club: "Real Madrid (ESP)" },
  { name: "Matheus Cunha", pos: "ATA", club: "Manchester United (ING)" },
  { name: "Igor Thiago", pos: "ATA", club: "Brentford (ING)" },
  { name: "Richarlison", pos: "ATA", club: "Tottenham (ING)" },
  { name: "Gabriel Jesus", pos: "ATA", club: "Arsenal (ING)" },
  { name: "Vitor Roque", pos: "ATA", club: "Real Betis (ESP)" },
  { name: "Evanilson", pos: "ATA", club: "Bournemouth (ING)" },
  { name: "Marcos Leonardo", pos: "ATA", club: "Benfica (POR)" },
  { name: "Pedro", pos: "ATA", club: "Flamengo (BRA)" },
  { name: "Gabigol", pos: "ATA", club: "Cruzeiro (BRA)" },
  { name: "Hulk", pos: "ATA", club: "Atlético-MG (BRA)" },
  { name: "Tiquinho Soares", pos: "ATA", club: "Botafogo (BRA)" },
  { name: "Flaco López", pos: "ATA", club: "Palmeiras (BRA)" },
  { name: "Alerrandro", pos: "ATA", club: "Vitória (BRA)" },
  { name: "Mastriani", pos: "ATA", club: "Athletico-PR (BRA)" },
  { name: "Anselmo Ramon", pos: "ATA", club: "CRB (BRA)" },
  { name: "Diego Costa", pos: "ATA", club: "Grêmio (BRA)" },
  { name: "Deyverson", pos: "ATA", club: "Atlético-MG (BRA)" },
  { name: "Pedro Raul", pos: "ATA", club: "Corinthians (BRA)" },
  { name: "Juan Martin Lucero", pos: "ATA", club: "Fortaleza (BRA)" },
  { name: "Arthur Cabral", pos: "ATA", club: "Benfica (POR)" },
  { name: "Willian José", pos: "ATA", club: "Spartak Moscou (RUS)" },
  { name: "Kauã Elias", pos: "ATA", club: "Fluminense (BRA)" },
  { name: "Luighi", pos: "ATA", club: "Palmeiras (BRA)" },
  { name: "Felipe Augusto", pos: "ATA", club: "Cercle Brugge (BEL)" },
  { name: "Pablo", pos: "ATA", club: "Athletico-PR (BRA)" },
  { name: "Rafael Borré", pos: "ATA", club: "Internacional (BRA)" },
  { name: "Jonathan Calleri", pos: "ATA", club: "São Paulo (BRA)" },
  { name: "Isidro Pitta", pos: "ATA", club: "Cuiabá (BRA)" },
  { name: "Igor Jesus", pos: "ATA", club: "Botafogo (BRA)" },
];

// Adiciona id único a cada jogador (slug + index pra evitar colisão de nomes repetidos)
PLAYERS.forEach((p, i) => {
  p.id = p.name.toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-") + "-" + i;
});

// =========================================================
// TÉCNICOS
// =========================================================
const COACHES = [
  // Estrangeiros
  { name: "Carlo Ancelotti", style: "Gestor de elenco, equilíbrio tático e vencedor nato", club: "Real Madrid (ESP)", group: "Estrangeiros" },
  { name: "Pep Guardiola", style: "Posicional, posse de bola extrema e revolução tática", club: "Manchester City (ING)", group: "Estrangeiros" },
  { name: "Abel Ferreira", style: "Competitivo, mentalidade vencedora e adaptável", club: "Palmeiras (BRA)", group: "Estrangeiros" },
  { name: "Jorge Jesus", style: "Ofensivo, pressão alta e intensidade máxima", club: "Al-Hilal (ARA)", group: "Estrangeiros" },
  { name: "Zinedine Zidane", style: "Gestão de vestiário estelar e pragmatismo em mata-mata", club: "Sem clube", group: "Estrangeiros" },
  { name: "Luis Enrique", style: "Posicional moderno, uso da base e intensidade", club: "PSG (FRA)", group: "Estrangeiros" },
  { name: "Lionel Scaloni", style: "Equilíbrio tático, pragmatismo e vencedor de Copa", club: "Seleção Argentina", group: "Estrangeiros" },
  { name: "Marcelo Bielsa", style: "Pressão asfixiante, jogo vertical e ofensivo", club: "Seleção Uruguaia", group: "Estrangeiros" },
  // Nacionais - elite
  { name: "Dorival Júnior", style: "Jogo de aproximação, ótimo gestor de grupo", club: "Sem clube", group: "Nacionais" },
  { name: "Renato Gaúcho", style: "Ofensivo, focado na individualidade e motivador", club: "Grêmio (BRA)", group: "Nacionais" },
  { name: "Tite", style: "Organização defensiva sólida e jogo apoiado", club: "Flamengo (BRA)", group: "Nacionais" },
  { name: "Rogério Ceni", style: "Jogo de triangulação, ofensivo e exigente taticamente", club: "Bahia (BRA)", group: "Nacionais" },
  { name: "Cuca", style: "Jogo vertical, forte em bolas paradas e motivador", club: "Sem clube", group: "Nacionais" },
  { name: "Mano Menezes", style: "Defensivo, reativo e focado no contra-ataque", club: "Fluminense (BRA)", group: "Nacionais" },
  // Nova geração
  { name: "Fernando Diniz", style: "Relacional, posse de bola autoral e risco na saída", club: "Cruzeiro (BRA)", group: "Nova geração" },
  { name: "Juan Pablo Vojvoda", style: "Moderno, intensidade física e transição rápida", club: "Fortaleza (BRA)", group: "Nova geração" },
  { name: "Artur Jorge", style: "Ofensivo, vertical e uso agressivo dos pontas", club: "Botafogo (BRA)", group: "Nova geração" },
  { name: "Luis Zubeldía", style: "Competitivo, copeiro e forte marcação", club: "São Paulo (BRA)", group: "Nova geração" },
  { name: "Filipe Luís", style: "Ideias modernas, ofensivo, influenciado pela Europa", club: "Flamengo (BRA)", group: "Nova geração" },
  { name: "Thiago Carpini", style: "Organização tática, transição rápida e nova escola", club: "Vitória (BRA)", group: "Nova geração" },
];

COACHES.forEach((c, i) => {
  c.id = c.name.toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-") + "-" + i;
});

// =========================================================
// FORMAÇÕES — cada slot tem posição base (x,y em % do campo) e a posição aceita
// Campo: 0,0 = canto superior esquerdo (linha de fundo do GOL), 100,100 = ataque
// =========================================================
const FORMATIONS = {
  "4-3-3": {
    label: "4-3-3",
    desc: "Equilíbrio com largura no ataque",
    slots: [
      { id: "GOL", pos: "GOL", x: 50, y: 6 },
      { id: "LD", pos: "LD", x: 84, y: 22 },
      { id: "ZAG1", pos: "ZAG", x: 64, y: 18 },
      { id: "ZAG2", pos: "ZAG", x: 36, y: 18 },
      { id: "LE", pos: "LE", x: 16, y: 22 },
      { id: "VOL1", pos: "VOL", x: 35, y: 42 },
      { id: "VOL2", pos: "VOL", x: 65, y: 42 },
      { id: "MEI", pos: "MEI", x: 50, y: 56 },
      { id: "PE", pos: "PE", x: 18, y: 78 },
      { id: "ATA", pos: "ATA", x: 50, y: 88 },
      { id: "PD", pos: "PD", x: 82, y: 78 },
    ],
  },
  "4-4-2": {
    label: "4-4-2",
    desc: "Clássico, dois de área e meio cheio",
    slots: [
      { id: "GOL", pos: "GOL", x: 50, y: 6 },
      { id: "LD", pos: "LD", x: 84, y: 22 },
      { id: "ZAG1", pos: "ZAG", x: 64, y: 18 },
      { id: "ZAG2", pos: "ZAG", x: 36, y: 18 },
      { id: "LE", pos: "LE", x: 16, y: 22 },
      { id: "PD", pos: "PD", x: 82, y: 50 },
      { id: "VOL1", pos: "VOL", x: 38, y: 46 },
      { id: "VOL2", pos: "VOL", x: 62, y: 46 },
      { id: "PE", pos: "PE", x: 18, y: 50 },
      { id: "ATA1", pos: "ATA", x: 38, y: 86 },
      { id: "ATA2", pos: "ATA", x: 62, y: 86 },
    ],
  },
  "3-5-2": {
    label: "3-5-2",
    desc: "Três zagueiros e alas avançados",
    slots: [
      { id: "GOL", pos: "GOL", x: 50, y: 6 },
      { id: "ZAG1", pos: "ZAG", x: 74, y: 18 },
      { id: "ZAG2", pos: "ZAG", x: 50, y: 14 },
      { id: "ZAG3", pos: "ZAG", x: 26, y: 18 },
      { id: "LD", pos: "LD", x: 88, y: 46 },
      { id: "VOL1", pos: "VOL", x: 38, y: 42 },
      { id: "VOL2", pos: "VOL", x: 62, y: 42 },
      { id: "LE", pos: "LE", x: 12, y: 46 },
      { id: "MEI", pos: "MEI", x: 50, y: 60 },
      { id: "ATA1", pos: "ATA", x: 38, y: 86 },
      { id: "ATA2", pos: "ATA", x: 62, y: 86 },
    ],
  },
  "4-2-3-1": {
    label: "4-2-3-1",
    desc: "Dois volantes de proteção e trio criativo",
    slots: [
      { id: "GOL", pos: "GOL", x: 50, y: 6 },
      { id: "LD", pos: "LD", x: 84, y: 22 },
      { id: "ZAG1", pos: "ZAG", x: 64, y: 18 },
      { id: "ZAG2", pos: "ZAG", x: 36, y: 18 },
      { id: "LE", pos: "LE", x: 16, y: 22 },
      { id: "VOL1", pos: "VOL", x: 38, y: 38 },
      { id: "VOL2", pos: "VOL", x: 62, y: 38 },
      { id: "PE", pos: "PE", x: 18, y: 64 },
      { id: "MEI", pos: "MEI", x: 50, y: 60 },
      { id: "PD", pos: "PD", x: 82, y: 64 },
      { id: "ATA", pos: "ATA", x: 50, y: 88 },
    ],
  },
  "3-4-3": {
    label: "3-4-3",
    desc: "Pressão alta e três atacantes",
    slots: [
      { id: "GOL", pos: "GOL", x: 50, y: 6 },
      { id: "ZAG1", pos: "ZAG", x: 74, y: 18 },
      { id: "ZAG2", pos: "ZAG", x: 50, y: 14 },
      { id: "ZAG3", pos: "ZAG", x: 26, y: 18 },
      { id: "LD", pos: "LD", x: 86, y: 44 },
      { id: "VOL1", pos: "VOL", x: 38, y: 42 },
      { id: "VOL2", pos: "VOL", x: 62, y: 42 },
      { id: "LE", pos: "LE", x: 14, y: 44 },
      { id: "PE", pos: "PE", x: 18, y: 80 },
      { id: "ATA", pos: "ATA", x: 50, y: 88 },
      { id: "PD", pos: "PD", x: 82, y: 80 },
    ],
  },
  "5-3-2": {
    label: "5-3-2",
    desc: "Linha defensiva reforçada, retranca elástica",
    slots: [
      { id: "GOL", pos: "GOL", x: 50, y: 6 },
      { id: "LD", pos: "LD", x: 88, y: 22 },
      { id: "ZAG1", pos: "ZAG", x: 68, y: 16 },
      { id: "ZAG2", pos: "ZAG", x: 50, y: 13 },
      { id: "ZAG3", pos: "ZAG", x: 32, y: 16 },
      { id: "LE", pos: "LE", x: 12, y: 22 },
      { id: "VOL1", pos: "VOL", x: 35, y: 46 },
      { id: "VOL2", pos: "VOL", x: 65, y: 46 },
      { id: "MEI", pos: "MEI", x: 50, y: 58 },
      { id: "ATA1", pos: "ATA", x: 38, y: 86 },
      { id: "ATA2", pos: "ATA", x: 62, y: 86 },
    ],
  },
};

// Posições legíveis em português
const POS_LABEL = {
  GOL: "Goleiro", LD: "Lateral-direito", ZAG: "Zagueiro", LE: "Lateral-esquerdo",
  VOL: "Volante", MEI: "Meia", PD: "Ponta-direita", PE: "Ponta-esquerda", ATA: "Atacante",
};
